### ISSUE TITLE
Feature request: Allow documentation in implementation section

### ISSUE THREAD

**Issue by piula** [pasdoc/pasdoc.github.io#3]
Hello,

personally, I like pasdoc much more than fpdoc because having the documentation together with the code imho makes it much easier to keep it up-to-date.

On the other hand, what I don't like is that it's required to put it in the interface section. I think it doesn't belong there because just as the code itself, I consider the documentation an implementation detail. Having it in the interface section makes the whole section very hard to read (because of its length) and hardens programing a lot. So I'm at the same point as with fpdoc again: I don't write any documentation :(

So my request is to allow users to place the documentation together with the code implementation. Ideally, this also should be allowed for simple types like "TMonth = (monJanuary, monFebruary)", but at least for all classes and its methods, properties, etc.

**Comment by michaliskambi** [comment]
We have this feature already :)

See https://pasdoc.github.io/ImplementationCommentsOption . Use the `--implementation-comments=xxx` command-line option to activate.

As for whether it's better to specify docs in interface or implementation: I know people that like both sides (and would never switch to another :) ), and in the end I consider it a matter of preference. PasDoc is committed to supporting both approaches. By default we support only comments in the interface, but many people requested and use the option to read comments also from implementation.

Some personal opinion (yeah, I prefer comments in interface :) ):

- On one hand, yes, comments in the interface make the interface longer.
- But you can say it also makes the interface more useful for person that wants to use the unit. That person can stop reading at `implementation` keyword.
- And you can always view short interface in PasDoc output.
- Comments that document how something works for people who use the unit are _not_ implementation detail IMHO, in the sense: it's a knowledge necessary for people who *use* your unit (in contrast to knowledge necessary only for people who implement the unit).

Neither of my above opinions is definite, though. As said, I can see it's just a matter of preference. In the end, if you write comments, it's most important to write them close to "where you expect them" so that they stay up-to-date.

P.S. https://github.com/pasdoc/pasdoc.github.io/ is a repository for our webpage. For PasDoc functionality, better to submit issues to https://github.com/pasdoc/pasdoc/ repo.
